version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Instalando kubectl..."
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo "Conectando ao cluster EKS..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - echo "Verificando conexão..."
      - kubectl get nodes

      # --- CORREÇÃO AQUI ---
      # Trocando a sintaxe de substring pela de 'cut'
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      
      - FULL_IMAGE_URI="${ECR_REPO_URL}:${IMAGE_TAG}"
      - echo "Fazendo deploy da imagem: $FULL_IMAGE_URI"

  build:
    commands:
      - echo "Atualizando o placeholder da imagem no deployment.yaml..."
      - sed -i "s|PLACEHOLDER_ECR_REPO_URL:latest|$FULL_IMAGE_URI|" deployment.yaml
      - echo "--- deployment.yaml atualizado ---"
      - cat deployment.yaml
      - echo "----------------------------------"
      - echo "Aplicando manifestos no EKS..."
      - kubectl apply -f deployment.yaml

  post_build:
    commands:
      - echo "Aguardando o rollout do deployment..."
      - kubectl rollout status deployment/alg2-todo-app-deploy
      - echo "Deploy concluído com sucesso!"
      - echo "Verificando o Service..."
      - kubectl get service alg2-todo-app-svc